version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: gomod
    rebase-strategy: auto
    assignees:
      - wuhuizuo
    reviewers:
      - wuhuizuo
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "16:07"
